export const emojiMap: { [key: string]: string } = {
  hamburguesa: '🍔',
  pizza: '🍕',
  sushi: '🍣',
  sandia: '🍉',
  manzana: '🍎',
  limon: '🍋',
  tomate: '🍅',
  pepino: '🥒',
  zanahoria: '🥕',
  pimiento: '🌶️',
  berenjena: '🍆',
  uva: '🍇',
  fresa: '🍓',
  kiwi: '🥝',
  piña: '🍍',
  naranja: '🍊',
  pera: '🍐',
  melón: '🍈',
  aguacate: '🥑',
  cebolla: '🧅',
  ajo: '🧄',
  batata: '🍠',
  maíz: '🌽',
  brócoli: '🥦',
  coliflor: '🥬',
  champiñón: '🍄',
};
